version: '3'
services:
  traefik:
    restart: unless-stopped
    container_name: traefik-leads
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  mysql:
    container_name: mysql-leads
    image: 'mysql:8.0.29'
    tty: true
    restart: unless-stopped
    networks:
      - web
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./docker/infra/mysql/entrypoint:/docker-entrypoint-initdb.d
      
  leads:
    container_name: leads
    build:
      context: ./docker/infra/php81
      dockerfile: Dockerfile
    networks:
      - web
    environment:
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - './projects/leads/:/var/www/html'
      - './docker/leads/.env:/var/www/html/.env'
    depends_on:
      - mysql
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.leads.rule=Host(`leads.local`)"
      - 'traefik.http.services.leads.loadbalancer.server.port=80'
networks:
  web:
    external: true